language: node_js
node_js:
  - 10
install:
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/tangle-frost/iota-core.git tangle-frost/iota-core
  - cd tangle-frost/iota-core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/tangle-frost/iota-qr-core.git tangle-frost/iota-qr-core
  - cd tangle-frost/iota-qr-core
  - npm link @tangle-frost/iota-core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/tangle-frost/iota-qr-render.git tangle-frost/iota-qr-render
  - cd tangle-frost/iota-qr-render
  - npm link @tangle-frost/iota-core @tangle-frost/iota-qr-core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/tangle-frost/iota-qr-data.git tangle-frost/iota-qr-data
  - cd tangle-frost/iota-qr-data
  - npm link @tangle-frost/iota-core @tangle-frost/iota-qr-core @tangle-frost/iota-qr-render
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/tangle-frost/iota-qr-lib.git tangle-frost/iota-qr-lib
  - cd tangle-frost/iota-qr-lib
  - npm link @tangle-frost/iota-core @tangle-frost/iota-qr-core @tangle-frost/iota-qr-render @tangle-frost/iota-qr-data
  - npm link
  - cd using-library/browser/data
  - npm link @tangle-frost/iota-qr-lib
  - npm install
  - cd ../../../using-library/browser/render-types
  - npm link @tangle-frost/iota-qr-lib
  - npm install
  - cd ../../../using-library/node-js/data
  - npm link @tangle-frost/iota-qr-lib
  - npm install
  - cd ../../../using-library/node-js/render-types
  - npm link @tangle-frost/iota-qr-lib
  - npm install
  - cd ../../../using-modules/browser/data
  - npm link @tangle-frost/iota-core @tangle-frost/iota-qr-core @tangle-frost/iota-qr-render @tangle-frost/iota-qr-data
  - npm install
  - cd ../../../using-modules/browser/render-types
  - npm link @tangle-frost/iota-core @tangle-frost/iota-qr-core @tangle-frost/iota-qr-render @tangle-frost/iota-qr-data
  - npm install
  - cd ../../../using-modules/node-js/data
  - npm link @tangle-frost/iota-core @tangle-frost/iota-qr-core @tangle-frost/iota-qr-render @tangle-frost/iota-qr-data
  - npm install
  - cd ../../../using-modules/node-js/render-types
  - npm link @tangle-frost/iota-core @tangle-frost/iota-qr-core @tangle-frost/iota-qr-render @tangle-frost/iota-qr-data
  - npm install
script:
  - cd ./using-library/browser/data
  - npm run build
  - cd ../../../using-library/browser/render-types
  - npm run build
  - cd ../../../using-library/node-js/data
  - npm run build
  - cd ../../../using-library/node-js/render-types
  - npm run build
  - cd ../../../using-modules/browser/data
  - npm run build
  - cd ../../../using-modules/browser/render-types
  - npm run build
  - cd ../../../using-modules/node-js/data
  - npm run build
  - cd ../../../using-modules/node-js/render-types
  - npm run build
